#!/usr/bin/env bash
# Detectar gerenciador de pacotes disponível
if command -v apt &> /dev/null; then
    PACKAGE_MANAGER="apt"
elif command -v yay &> /dev/null; then
    PACKAGE_MANAGER="yay"
else
    echo "Gerenciador de pacotes não suportado. O script suporta apenas apt e yay."
    exit 1
fi

echo "Gerenciador de pacotes detectado: $PACKAGE_MANAGER"

# Instalar dependências com base no gerenciador de pacotes
if [[ "$PACKAGE_MANAGER" == "apt" ]]; then
    echo "Instalando pacotes para o wsl com apt..."
        while read -r package; do
            sudo apt install -y $package || echo "Package $package not found."
        done < wsl-ubuntu.txt
elif [[ "$PACKAGE_MANAGER" == "yay" ]]; then
    echo "Instalando pacotes para wsl com yay..."
        yay -S --noconfirm --needed - < wsl-arch.txt        
fi
