#!/bin/bash

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
else
    OS=$(uname -s)
fi

case $OS in
    "Ubuntu")
        while read -r package; do
            sudo nala install -y "$package" || echo "Package $package not found."
        done < wsl-ubuntu.txt
        ;;
    "Arch Linux")
        yay -S --noconfirm --needed - < wsl-arch.txt
        ;;
    *)
        echo "Error"
        ;;
esac
