# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Cross-platform software keyboard remapper for Linux, macOS and Windows
brew "kanata"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# AI coding agent, built for the terminal
brew "opencode"
# Smart session manager for the terminal
brew "sesh"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Terminal multiplexer
brew "tmux"
# Command-line interface to the freedesktop.org trashcan
brew "trash-cli"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Terminal interface for Antigravity agents
cask "antigravity-cli"
cask "font-cascadia-mono"
cask "font-hack-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-symbols-only-nerd-font"
